name: Producer Subir CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS (IAM)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Subir CSV al bucket upeu-bucket-entrada
        run: |
          aws s3 cp DataCovid.csv s3://upeu-bucket-entrada/ --acl bucket-owner-full-control