name: Producer Subir CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS (IAM)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validar si el bucket existe y subir CSV
        run: |
          if aws s3api head-bucket --bucket upeu-bucket-entrada 2>/dev/null; then
            echo " El bucket existe. Subiendo archivo..."
            aws s3 cp DataCovid.csv s3://upeu-bucket-entrada/ --acl bucket-owner-full-control
          else
            echo " El bucket upeu-bucket-entrada no existe o no tienes permiso."
            exit 1
          fi